/**
 * UI CONSTANTS
 */
export const ADD_AGENT_WINDOW_CLOSE_REQUEST = "ADD_AGENT_WINDOW_CLOSE_REQUEST"

/**
 * DATABASE CONSTANTS
 */

// TABLES
export const DB_TABLE_AGENTS = 'agents'
export const DB_TABLE_PARTNERS = 'partenaires'

// OPERATIONS
export const DB_GET_ALL_AGENTS = "DB_GET_ALL_AGENTS"
export const DB_ADD_AGENT = 'DB_ADD_AGENT'
export const DB_ADD_PARTNER = "DB_ADD_PARTNER"

// RESULTS
export const DB_OP_SUCCESS = "DB_OP_SUCCESS"
export const DB_OP_FAILURE = "DB_OP_FAILURE"