/**
 * UI CONSTANTS
 */
export const ADD_AGENT_WINDOW_CLOSE_REQUEST = "ADD_AGENT_WINDOW_CLOSE_REQUEST"

/**
 * DATABASE CONSTANTS
 */

// TABLES
export const DB_TABLE_AGENTS = 'agents'
export const DB_TABLE_PARTNERS = 'partenaires'
export const DB_TABLE_AGENTS_DETTES = 'agents_dettes'
export const DB_TABLE_PAYMENTS = 'payments'

// OPERATIONS
export const DB_GET_ALL_AGENTS = "DB_GET_ALL_AGENTS"
export const DB_ADD_AGENT = 'DB_ADD_AGENT'
export const DB_ADD_PARTNER = "DB_ADD_PARTNER"

// RESPONSES
export const DB_RESPONSE_GET_ALL_AGENTS = "DB_RESPONSE_GET_ALL_AGENTS"
export const DB_RESPONSE_ADD_AGENT = 'DB_RESPONSE_ADD_AGENT'
export const DB_RESPONSE_ADD_PARTNER = "DB_RESPONSE_ADD_PARTNER"

// RESULTS
export const DB_OP_SUCCESS = "DB_OP_SUCCESS"
export const DB_OP_FAILURE = "DB_OP_FAILURE"